[font]
size = 13
offset.y = 8

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window]
opacity = 0.90

[scrolling]
history = 99999

[env]
TERM = "xterm-256color"
